name: 1.12.2 Build

on:
  pull_request:
  push:
    branches:
      - "mainline"

env:
  WORLDMAP_VERSION: "1.39.0"
  MINIMAP_VERSION: "24.5.0"
  MINECRAFT_VERSION: "1.12.2"
  MINECRAFT_VERSION_SHORT: "1.12"
  MOD_LOADER: "Forge"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Rename built mod
        run: mv build/libs/xaeroplus-${{ env.MINECRAFT_VERSION }}.jar XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}
          path: XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar

      - name: Set CI Test Env Var
        run: echo "XP_CI_TEST=true" >> $GITHUB_ENV

      - name: Setup Forge Test
        run: |
          mkdir -p run/mods && cp XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar run/mods \
          && wget https://api.modrinth.com/maven/maven/modrinth/xaeros-minimap/${{ env.MINIMAP_VERSION }}_Forge_1.12/xaeros-minimap-${{ env.MINIMAP_VERSION }}_Forge_1.12.jar -P run/mods/ \
          && wget https://api.modrinth.com/maven/maven/modrinth/xaeros-world-map/${{ env.WORLDMAP_VERSION }}_Forge_1.12/xaeros-world-map-${{ env.WORLDMAP_VERSION }}_Forge_1.12.jar -P run/mods/

      - name: Forge Test
        uses: 3arthqu4ke/mc-runtime-test@2.3.1
        with:
          mc: ${{ env.MINECRAFT_VERSION }}
          modloader: forge
          regex: .*forge.*
          mc-runtime-test: lexforge
          java: 8
          xvfb: false
          headlessmc-command: -lwjgl --jvm -Djava.awt.headless=true
